#!/usr/bin/env node
import path from 'path';
import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { compileFromFile } from 'json-schema-to-typescript'
import directoryTree from 'directory-tree';
import fs from "fs";

const __dirname = dirname(fileURLToPath(import.meta.url));

let dest = process.argv[2];

if (!dest) {
  throw new Error('missing dest parameter');
}
dest = path.join(__dirname, dest);
dest = path.join(dest, '../../../dist-schema/');
if (!fs.existsSync(dest)){
  fs.mkdirSync(dest, { recursive: true });
}
dest = path.join(dest, 'types.d.ts');

const src = path.join(__dirname, '../../src/schemas');



fs.writeFileSync(dest, "/* tslint:disable */\n/* eslint:disable */\n/** Please note that any changes in this file may be overwritten, do not edit this file manually. This file is auto-generated. **/\n\n");

directoryTree(src, { extensions: /\.json$/ }, (item) => {

  compileFromFile(item.path, { 
    bannerComment: "// ----------------------------------------------- " 
  })
    .then(ts => fs.appendFileSync(dest, ts));
})

